birdseye:
  enabled: false

cameras:
  bedroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:HASScamera@10.77.77.161:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      enabled: false
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: false
  living_room:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:HASScamera@10.77.77.102:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - detect
            - record
    detect:
      enabled: false
      width: 2592
      height: 1944
    record:
      enabled: true
    snapshots:
      enabled: false

mqtt:
  enabled: false
