esphome:
  name: living_room
  friendly_name: living_room

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret LIVING-ROOM_API_ENCRYPTION_KEY

ota:
  - platform: esphome
    password: !secret LIVING-ROOM_OTA_PASSWORD

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: True

bluetooth_proxy:
  active: True
