esphome:
  name: living_room
  friendly_name: living_room

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret LIVING-ROOM_API_ENCRYPTION_KEY

ota:
  - platform: esphome
    password: !secret LIVING-ROOM_OTA_PASSWORD

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: True

# bluetooth_proxy:
#   active: True

sensor:
- platform: xiaomi_hhccjcy01
  mac_address: 'C4:7C:8D:6C:1F:3B'
  temperature:
    name: "Baby Rubberplant Temperature"
  moisture:
    name: "Baby Rubberplant Moisture"
  illuminance:
    name: "Baby Rubberplant Illuminance"
  conductivity:
    name: "Baby Rubberplant Soil Conductivity"
  battery_level:
    name: "Baby Rubberplant Battery Level"
- platform: xiaomi_hhccjcy01
  mac_address: 'C4:7C:8D:6D:3C:A7'
  temperature:
    name: "Pothos Temperature"
  moisture:
    name: "Pothos Moisture"
  illuminance:
    name: "Pothos Illuminance"
  conductivity:
    name: "Pothos Soil Conductivity"
  battery_level:
    name: "Pothos Battery Level"
- platform: xiaomi_hhccjcy01
  mac_address: 'C4:7C:8D:6D:3E:A6'
  temperature:
    name: "Snake Plant (Left) Temperature"
  moisture:
    name: "Snake Plant (Left) Moisture"
  illuminance:
    name: "Snake Plant (Left) Illuminance"
  conductivity:
    name: "Snake Plant (Left) Soil Conductivity"
  battery_level:
    name: "Snake Plant (Left) Battery Level"
- platform: xiaomi_hhccjcy01
  mac_address: '5C:85:7E:13:2E:F1'
  temperature:
    name: "Snake Plant (Right) Temperature"
  moisture:
    name: "Snake Plant (Right) Moisture"
  illuminance:
    name: "Snake Plant (Right) Illuminance"
  conductivity:
    name: "Snake Plant (Right) Soil Conductivity"
  battery_level:
    name: "Snake Plant (Right) Battery Level"
- platform: xiaomi_hhccjcy01
  mac_address: '5C:85:7E:13:32:D3'
  temperature:
    name: "Monstera Temperature"
  moisture:
    name: "Monstera Moisture"
  illuminance:
    name: "Monstera Illuminance"
  conductivity:
    name: "Monstera Soil Conductivity"
  battery_level:
    name: "Monstera Battery Level"
